class GameLogic:
    def __init__(self):
        self.combinations = {
            "Fuoco+Acqua": "Vapore",
            "Fuoco+Terra": "Metallo",
            "Fuoco+Aria": "Esplosione",
            "Fuoco+Fuoco": "Fuoco",
            "Fuoco+Mare": "Sale",
            "Acqua+Fuoco": "Vapore",
            "Acqua+Terra": "Pianta",
            "Acqua+Aria": "Pioggia",
            "Acqua+Acqua": "Mare",
            "Acqua+Metallo": "Ruggine",
            "Acqua+Lava": "Ossidiana",
            "Terra+Fuoco": "Metallo",
            "Terra+Acqua": "Pianta",
            "Terra+Aria": "Sabbia",
            "Terra+Terra": "Pianeta",
            "Aria+Fuoco": "Esplosione",
            "Aria+Acqua": "Pioggia",
            "Aria+Terra": "Sabbia",
            "Aria+Aria": "Cielo",
            "Vapore+Fuoco": "Motore",
            "Vapore+Terra": "Fango",
            "Vapore+Acqua": "Nuvola",
            "Vapore+Aria": "Nuvola",
            "Vapore+Esplosione": "Bomba",
            "Vapore+Pioggia": "Nuvola",
            "Vapore+Sabbia": "Terra",
            "Vapore+Cielo": "Nuvola",
            "Vapore+Bomba": "Esplosione",
            "Vapore+Cenere": "Fumo",
            "Vapore+Foglia": "Vita",
            "Sabbia+Fuoco": "Vetro",
            "Sabbia+Acqua": "Fango",
            "Sabbia+Terra": "Palla",
            "Sabbia+Vapore": "Terra",
            "Sabbia+Pioggia": "Fango",
            "Sabbia+Pianta": "Cactus",
            "Sabbia+Bomba": "Esplosione",
            "Sabbia+Vetro": "Orologio",
            "Metallo+Fuoco": "Lava",
            "Metallo+Sabbia": "Orologio",
            "Metallo+Esplosione": "Bomba",
            "Metallo+Orologio": "PC",
            "Metallo+Vita": "Robot",
            "Esplosione+Fuoco": "Bomba",
            "Esplosione+Acqua": "Vapore",
            "Esplosione+Metallo": "Bomba",
            "Esplosione+Pioggia": "Vapore",
            "Esplosione+Vapore": "Bomba",
            "Esplosione+Esplosione": "Nucleare",
            "Esplosione+Cielo": "Bomba",
            "Esplosione+Vetro": "Bomba",
            "Pianta+Acqua": "Foglia",
            "Pianta+Terra": "Foglia",
            "Pianta+Sabbia": "Cactus",
            "Pianta+Pioggia": "Vita",
            "Pianta+Pianta": "Albero",
            "Pianta+Foglia": "Libro",
            "Pioggia+Fuoco": "Vapore",
            "Pioggia+Terra": "Fango",
            "Pioggia+Acqua": "Mare",
            "Pioggia+Aria": "Fulmine",
            "Pioggia+Sabbia": "Fango",
            "Pioggia+Vapore": "Nuvola",
            "Pioggia+Esplosione": "Vapore",
            "Pioggia+Pianta": "Vita",
            "Cielo+Fuoco": "Stella",
            "Cielo+Terra": "Fango",
            "Cielo+Aria": "Fulmine",
            "Cielo+Vapore": "Nuvola",
            "Cielo+Esplosione": "Bomba",
            "Cielo+Fango": "Pioggia",
            "Fulmine+Aria": "Pioggia",
            "Fulmine+Metallo": "Lampadina",
            "Foglia+Acqua": "Foglia",
            "Foglia+Terra": "Foglia",
            "Foglia+Vapore": "Vita",
            "Foglia+Pianta": "Libro",
            "Bomba+Sabbia": "Esplosione",
            "Bomba+Pioggia": "Vapore",
            "Vita+Metallo": "Robot",
            "Libro+Pianta": "Libro",
            "Orologio+Metallo": "PC",
            "Mare+Metallo": "Ruggine",
        }
        self.special_combinations = {
            "Mare+Stella": "Patrick",
            "Orologio+Cactus": "Lirili LariLa",
            "Stella+Palla": "Yamal",
            "Stella+Mare": "Patrick",
            "Libro+Robot": "Sottile",
            "Libro+PC": "Andrea Pollini",
            "Robot+Libro": "Sottile",
            "Robot+Vita": "Eva 0-1",
            "PC+Libro": "Andrea Pollini",
            "Vita+Robot": "Eva 0-1",
            "Cactus+Orologio": "Lirili Lari La",
            "Albero+Terra": "Fungo Porcino",
            "Palla+Stella": "Yamal",
            "Vita+Terra": "Steve",
            "Bomba+Metallo": "Mortaio di Clash Royale",
            "Foglia+Fulmine": "Minato Namikaze",
            "Fulmine+Foglia": "Minato Namikaze",
            "Metallo+Bomba": "Mortaio di Clash Royale",
            "Terra+Vita": "Steve",
            "Terra+Albero": "Fungo Porcino"
        }

    def combine_elements(self, element1, element2):
        key1 = f"{element1}+{element2}"
        key2 = f"{element2}+{element1}"
        if key1 in self.special_combinations or key2 in self.special_combinations:
            return self.special_combinations.get(key1) or self.special_combinations.get(key2), 5
        elif key1 in self.combinations or key2 in self.combinations:
            return self.combinations.get(key1) or self.combinations.get(key2), 1
        else:
            return None, 0